[package]
name = "generate-event"
version = "0.1.0"
authors = ["Diego Rubin <rubin.diego@gmail.com>"]
edition = "2018"

[dependencies]
amiquip = { version = "0.3", default-features = false }
rdkafka = { version = "0.23", features = ["cmake-build"] }
